import type { Metadata } from "next";

import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import Navbar from "@/components/shared/navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Fix It Now",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
 
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-right" />
    {/* <Navbar/> */}

        {children}

        {/* footer */}
      </body>
    </html>
  );
}
